#! /bin/sh

sxhkd &
xscreensaver &
feh --bg-center --bg-fill "${HOME}/.config/bspwm/background.jpg" &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          0
bspc config active_border_color #000000
bspc config normal_border_color #000000

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       any
