#! /bin/sh

sxhkd &
#panel &
xscreensaver &
#conky &
feh --bg-center --bg-fill $HOME/.config/bspwm/background.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          0
bspc config active_border_color #E84F4F
bspc config normal_border_color #000000

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       any

WAIT_TIME=0.5

chromium &
sleep $WAIT_TIME
#bspc node -p {west,south,north,east}
bspc node -p west
sleep $WAIT_TIME
terminator &
sleep $WAIT_TIME
bspc node -p south
sleep $WAIT_TIME
subl
